prac_compo: prac_compo.cpp Rectangulo.o
    g++ prac_como.cpp Rectangulo.o Coordenada.o -o prac_compo
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
    g++ Rectangulo.cpp -c
Coordenada.o: Coordeanda.cpp Coordenada.h
    g+ Coordeanda.cpp -c